---
services:
  container-manager-mcp:
    image: docker.io/knucklessg1/container-manager:latest
    # build: . # Debug
    container_name: container-manager-mcp
    hostname: container-manager-mcp
    command: ["container-manager-mcp"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "HOST=0.0.0.0"
      - "PORT=8019"
      - "TRANSPORT=streamable-http"
      - "CONTAINER_MANAGER_TYPE=docker"
    #      - AUTH_TYPE=oidc-proxy # Optional
    #      - OIDC_CONFIG_URL=https://provider.com/.well-known/openid-configuration # Optional
    #      - OIDC_CLIENT_ID=your-client-id # Optional
    #      - OIDC_CLIENT_SECRET=your-client-secret # Optional
    #      - OIDC_BASE_URL=https://your-server.com # Optional
    #      - ALLOWED_CLIENT_REDIRECT_URIS=http://localhost:*,https://*.example.com/* # Optional
    #      - ENABLE_DELEGATION=True # Optional
    #      - AUDIENCE=https://yourinstance.gitlab.com # Optional
    #      - DELEGATED_SCOPES='api user_impersonation' # Optional
    #      - EUNOMIA_TYPE=embedded # Optional
    #      - EUNOMIA_POLICY_FILE=/app/mcp_policies.json # Optional
    #      - FASTMCP_SERVER_AUTH_JWT_ALGORITHM=HS256 # Optional
    #      - FASTMCP_SERVER_AUTH_JWT_PUBLIC_KEY=your-shared-secret # Optional
    #      - FASTMCP_SERVER_AUTH_JWT_REQUIRED_SCOPES=gitlab.read,gitlab.write # Optional
    ports:
      - "8019:8019"

  container-manager-agent:
    image: docker.io/knucklessg1/container-manager:latest
    # build: . # Debug
    container_name: container-manager-agent
    hostname: container-manager-agent
    command: ["container-manager-agent"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - container-manager-mcp
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    environment:
      - "HOST=0.0.0.0"
      - "PORT=9019"
      # - "MCP_CONFIG=./container_manager_mcp/mcp_config.json" # Optionally specify your own file - Default will use MCP_URL in the pre-packaged mcp_config.json
      - "MCP_URL=http://container-manager-mcp:8019/mcp"
      - "PROVIDER=openai"
      - "OPENAI_BASE_URL=http://host.docker.internal:1234/v1"
      - "OPENAI_API_KEY=llama"
      - "MODEL_ID=qwen/qwen3-4b-2507"
      - "DEBUG=False"
      - "ENABLE_WEB_UI=True"
    ports:
      - "9019:9019"
