[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "container-manager-mcp"
version = "1.3.17"
description = "Container Manager - manage Docker, Docker Swarm, and Podman containers. MCP+A2A Servers Out of the Box!"
readme = "README.md"
authors = [{ name = "Audel Rouhi", email = "knucklessg1@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Public Domain",
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "agent-utilities[mcp]>=0.2.4",
    "docker>=7.1.0",
]

[project.optional-dependencies]
podman = [
    "podman>=5.6.0",
]
docker = [
    "docker>=7.1.0",
]
mcp = [
    "agent-utilities[mcp]>=0.2.4",
]
agent = [
    "agent-utilities[agent,logfire]>=0.2.4",
    "container-manager-mcp[mcp]>=1.3.17",
]
all = [
    "container-manager-mcp[docker,podman,mcp,agent]>=1.3.17",
]

[project.scripts]
container-manager = "container_manager_mcp.container_manager:container_manager"
container-manager-mcp = "container_manager_mcp.mcp:mcp_server"
container-manager-agent = "container_manager_mcp.agent:agent_server"


[tool.setuptools.package-data]
container_manager_mcp = [ "mcp_config.json", "skills/**", "agent/**",]

[tool.setuptools.packages.find]
where = ["."]
